openapi: 3.0.0
info:
  title: GitHub Profile Checker API
  version: 1.0.0
  description: GitHub Profile CheckerのAPI仕様書です。
servers:
  - url: http://localhost:3000
    description: Development server
  - url: https://vercel-todo.com
    description: Production server
paths:
  /api/search:
    get:
      summary: GitHubリポジトリを検索する
      tags:
        - Github Repository APIs
      parameters:
        - in: query
          name: q
          required: true
          schema:
            type: string
          description: 検索クエリ
          example: some_keyword_here
        - in: query
          name: page
          schema:
            type: integer
          description: ページ目
          example: 5
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  total_pages:
                    type: integer
                    description: ページ数（1ページは最大30項目）
                  total_count:
                    type: integer
                    description: 結果件数
                  result:
                    type: array
                    items:
                      type: object
                      properties:
                        avatar_url:
                          type: string
                          description: ユーザーのアバターURL
                        repository_name:
                          type: string
                          description: リポジトリ名
                        user_name:
                          type: string
                          description: ユーザー名
                    description: 検索結果の配列
                required:
                  - total_pages
                  - total_count
                  - result
              example:
                total_pages: 2
                total_count: 42
                result:
                  - avatar_url: 'https://avatars.githubusercontent.com/u/7286214?v=4'
                    repository_name: 'github-profile-checker'
                    user_name: 'PerryM123'
                  - avatar_url: 'https://avatars.githubusercontent.com/u/7286214?v=4'
                    repository_name: 'memories_backend'
                    user_name: 'PerryM123'
                  - avatar_url: 'https://avatars.githubusercontent.com/u/7286214?v=4'
                    repository_name: 'split-my-receipt-up-frontend'
                    user_name: 'PerryM123'
                  - avatar_url: 'https://avatars.githubusercontent.com/u/7286214?v=4'
                    repository_name: 'take-home-assignment'
                    user_name: 'PerryM123'
                  - avatar_url: 'https://avatars.githubusercontent.com/u/7286214?v=4'
                    repository_name: 'image-compressor'
                    user_name: 'PerryM123'
                  - avatar_url: 'https://avatars.githubusercontent.com/u/7286214?v=4'
                    repository_name: 'split-my-receipt-up-swagger-doc'
                    user_name: 'PerryM123'
                  - avatar_url: 'https://avatars.githubusercontent.com/u/7286214?v=4'
                    repository_name: 'open-ai-api-mock-environment'
                    user_name: 'PerryM123'
                  - avatar_url: 'https://avatars.githubusercontent.com/u/7286214?v=4'
                    repository_name: 'Change-To-Old-Reddit'
                    user_name: 'PerryM123'
                  - avatar_url: 'https://avatars.githubusercontent.com/u/7286214?v=4'
                    repository_name: 'ranking-project'
                    user_name: 'PerryM123'
                  - avatar_url: 'https://avatars.githubusercontent.com/u/7286214?v=4'
                    repository_name: 'my-download-box-frontend'
                    user_name: 'PerryM123'
                  - avatar_url: 'https://avatars.githubusercontent.com/u/7286214?v=4'
                    repository_name: 'check-room-temp-frontend'
                    user_name: 'PerryM123'
                  - avatar_url: 'https://avatars.githubusercontent.com/u/7286214?v=4'
                    repository_name: 'check-room-temp'
                    user_name: 'PerryM123'
                  - avatar_url: 'https://avatars.githubusercontent.com/u/7286214?v=4'
                    repository_name: 'my-download-box-backend'
                    user_name: 'PerryM123'
                  - avatar_url: 'https://avatars.githubusercontent.com/u/7286214?v=4'
                    repository_name: 'splitting-the-cost'
                    user_name: 'PerryM123'
                  - avatar_url: 'https://avatars.githubusercontent.com/u/7286214?v=4'
                    repository_name: 'tekken-frame-data-admin'
                    user_name: 'PerryM123'
                  - avatar_url: 'https://avatars.githubusercontent.com/u/7286214?v=4'
                    repository_name: 'tekken-frame-data-backend'
                    user_name: 'PerryM123'
                  - avatar_url: 'https://avatars.githubusercontent.com/u/7286214?v=4'
                    repository_name: 'tekken-frame-data'
                    user_name: 'PerryM123'
                  - avatar_url: 'https://avatars.githubusercontent.com/u/7286214?v=4'
                    repository_name: 'BluePrintAlarmClock'
                    user_name: 'PerryM123'
                  - avatar_url: 'https://avatars.githubusercontent.com/u/7286214?v=4'
                    repository_name: 'Game-Center-Search-App'
                    user_name: 'PerryM123'
                  - avatar_url: 'https://avatars.githubusercontent.com/u/7286214?v=4'
                    repository_name: 'my-fun-express-server'
                    user_name: 'PerryM123'
                  - avatar_url: 'https://avatars.githubusercontent.com/u/7286214?v=4'
                    repository_name: 'nextJsProject'
                    user_name: 'PerryM123'
                  - avatar_url: 'https://avatars.githubusercontent.com/u/7286214?v=4'
                    repository_name: 'meetup-tsuu'
                    user_name: 'PerryM123'
                  - avatar_url: 'https://avatars.githubusercontent.com/u/7286214?v=4'
                    repository_name: 'Music-Note-Fingering-Practice'
                    user_name: 'PerryM123'
                  - avatar_url: 'https://avatars.githubusercontent.com/u/7286214?v=4'
                    repository_name: 'fun-with-es6-and-typescript'
                    user_name: 'PerryM123'
                  - avatar_url: 'https://avatars.githubusercontent.com/u/7286214?v=4'
                    repository_name: 'testing-jest-and-enzyme'
                    user_name: 'PerryM123'
                  - avatar_url: 'https://avatars.githubusercontent.com/u/7286214?v=4'
                    repository_name: 'Having-fun-playing-with-ajax'
                    user_name: 'PerryM123'
                  - avatar_url: 'https://avatars.githubusercontent.com/u/7286214?v=4'
                    repository_name: 'Practicing-Touch-and-Mouse-Events'
                    user_name: 'PerryM123'
                  - avatar_url: 'https://avatars.githubusercontent.com/u/7286214?v=4'
                    repository_name: 'User-List-App'
                    user_name: 'PerryM123'
                  - avatar_url: 'https://avatars.githubusercontent.com/u/7286214?v=4'
                    repository_name: 'React-Redux-Practice'
                    user_name: 'PerryM123'
                  - avatar_url: 'https://avatars.githubusercontent.com/u/7286214?v=4'
                    repository_name: 'fun-with-fetch-js-and-reactjs'
                    user_name: 'PerryM123'
        '400':
          description: 必須パラメータは足りてません
          content:
            application/json:
              schema:
                type: object
                properties:
                  error_message:
                    type: string
                    example: qのパラメータは足りてません
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error_message:
                    type: string
                    example: An unexpected error occurred
